### Train model on defined inputs and outputs



In [34]:
import numpy as np

# Sigmoid function

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Sigmoid derivatives

def sigmoid_derivative(x):
    return x * (1 - x)

# define training inputs
training_inputs = np.array([[0,0,1],
                           [1,1,1],
                           [1,0,1],
                           [0,1,1]])

# define the training outputs
training_outputs = np.array([[0,1,1,0]]).T #transpose the row to get a 4x4 matrix


# Initialize weights

np.random.seed(1)

synaptic_weights = 2 + np.random.random((3, 1)) - 1

print ('Random starting synaptic starting weights: ')
print(synaptic_weights)

# main loop over 20.000 iterations or higher. 
# outputs after training will come close to the real outputs, since we adjust for the errors. 
# Small numbers = low confidence, high numbers = high confidence (gradient)

for iteration in range(100000):
    
    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    
    error = training_outputs - outputs
    
    adjustments = error * sigmoid_derivative(outputs)
    
    synaptic_weights += np.dot(input_layer.T, adjustments)
    
print('Synaptic weights after training: ')
print(synaptic_weights)
    
    
print('Outputs after training: ')
print(outputs)

Random starting synaptic starting weights: 
[[1.417022  ]
 [1.72032449]
 [1.00011437]]
Synaptic weights after training: 
[[12.00871375]
 [-0.20435961]
 [-5.80031978]]
Outputs after training: 
[[0.00301747]
 [0.9975373 ]
 [0.99799156]
 [0.00246112]]


### make the training model usable.

In [38]:
# Define a class

class NeuralNetwork():
    
    def __init__(self):
        np.random.seed(1)
        
        self.synaptic_weights = 2 + np.random.random((3, 1)) - 1 # 3x1 matrix with all values between 1 and 0 with a mean of 0
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def train(self, training_inputs, training_outputs, training_iterations):
        
        for iteration in range(training_iterations):
            
            output = self.think(training_inputs)
            
            error = training_outputs - output
            
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))
            
            self.synaptic_weights += adjustments
    
    def think(self, inputs):
        
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        
        return output
    
if __name__ == "__main__":
    
    neural_network = NeuralNetwork()
    
    print('Random synaptic weights: ')
    print(neural_network.synaptic_weights)
    
    training_inputs = np.array([[1,1,1],
                               [0,0,0],
                               [1,1,0],
                               [0,0,1]])
    
    training_outputs = np.array([[1,0,0,1]]).T
    
    neural_network.train(training_inputs, training_outputs, 25000)
    
    print('Synaptic weights after training: ')
    print(neural_network.synaptic_weights)
    
    A = str(input('input 1: '))
    B = str(input('input 2: '))
    C = str(input('input 3: '))
    
    print('New situation: input data = ', A, B, C)
    print('Output data: ')
    print(neural_network.think(np.array([A, B, C])))
    

Random synaptic weights: 
[[1.417022  ]
 [1.72032449]
 [1.00011437]]
Synaptic weights after training: 
[[-2.61705668]
 [-2.31375419]
 [ 9.97440746]]
input 1: 1
input 2: 0
input 3: 0
New situation: input data =  1 0 0
Output data: 
[0.06804872]
